# Generated by Django 3.2 on 2023-11-01 18:49

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['username'], 'verbose_name': 'Участники', 'verbose_name_plural': 'Участники'},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='user', max_length=9),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_forbidden_username]),
        ),
    ]
