# Generated by Django 3.2 on 2023-11-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231101_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('username',), 'verbose_name': 'Участники', 'verbose_name_plural': 'Участники'},
        ),
    ]
