# Generated by Django 3.2 on 2023-10-30 20:55

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20231030_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.validate_forbidden_username]),
        ),
    ]
